name: Build Static GDB 9.2 for MIPSEL

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential \
            wget \
            bison \
            flex \
            texinfo \
            git \
            gcc-mipsel-linux-gnu \
            g++-mipsel-linux-gnu \
            libc6-dev-mipsel-cross \
            libexpat1-dev \
            libncurses5-dev \
            libxml2-dev \
            python3 \
            python3-pip

      - name: Download GDB 9.2
        run: |
          wget https://ftp.gnu.org/gnu/gdb/gdb-9.2.tar.gz
          tar -xzf gdb-9.2.tar.gz
          cd gdb-9.2
          

      - name: Build and install GDB
        run: |
          cd gdb-9.2
          ./configure --host=mipsel-linux-gnu --enable-static --disable-shared
          make
          make install DESTDIR=$GITHUB_WORKSPACE/gdb-output

      - name: Archive GDB
        run: |
          cd $GITHUB_WORKSPACE/gdb-output
          tar -czf gdb-9.2-mipsel-static.tar.gz .

      - name: Upload GDB Artifact
        uses: actions/upload-artifact@v3
        with:
          name: gdb-9.2-mipsel-static
          path: $GITHUB_WORKSPACE/gdb-output/gdb-9.2-mipsel-static.tar.gz
