name: Build Static GDB 7.2

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential texinfo

      - name: Download GDB 7.2
        run: |
          wget http://ftp.gnu.org/gnu/gdb/gdb-7.2.tar.gz
          tar -xzvf gdb-7.2.tar.gz
          cd gdb-7.2

      - name: Build GDB
        run: |
          cd gdb-7.2
          ./configure --enable-static --disable-shared
          make
          sudo make install

      - name: Verify GDB installation
        run: |
          gdb --version
