name: Build GDB for MIPSEL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            g++-mipsel-linux-gnu \
            binutils-mipsel-linux-gnu \
            texinfo \
            git \
            libc6-dev-mipsel-cross \
            libgcc-8-dev-mipsel-cross \
            libstdc++-8-dev-mipsel-cross \
            mipsel-linux-gnu-gcc \
            mipsel-linux-gnu-g++ \
            musl-tools  # 可选，提供静态链接支持

      - name: Download GDB source
        run: |
          wget http://ftp.gnu.org/gnu/gdb/gdb-9.2.tar.gz
          tar -xzvf gdb-9.2.tar.gz
          cd gdb-9.2

      - name: Build GDB
        run: |
          cd gdb-9.2
          ./configure --target=mipsel-linux-gnu --enable-static --disable-shared
          make

      - name: Install GDB
        run: |
          cd gdb-9.2
          make install DESTDIR=./gdb-install

      - name: Upload GDB artifact
        uses: actions/upload-artifact@v3
        with:
          name: gdb
          path: gdb-install
