name: Build GDB for MIPSEL

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            build-essential \
            git \
            wget \
            bison \
            flex \
            texinfo \
            gcc-mipsel-linux-gnu \
            g++-mipsel-linux-gnu \
            libc6-dev-mipsel-cross \
            musl-tools

      - name: Download GDB source
        run: |
          wget http://ftp.gnu.org/gnu/gdb/gdb-9.2.tar.gz
          tar -xzvf gdb-9.2.tar.gz

      - name: Build GDB
        run: |
          mkdir gdb-9.2-build
          cd gdb-9.2-build
          ../gdb-9.2/configure --target=mipsel-linux-gnu --enable-static --disable-shared --prefix=$HOME/gdb_install
          make
          echo "Build completed."

      - name: Install GDB
        run: |
          cd gdb-9.2-build
          make install
          echo "Installation completed."

      - name: List installed files
        run: |
          ls -la $HOME/gdb_install/bin || echo "No files found in gdb_install/bin."

      - name: Find gdbserver globally
        id: find_gdbserver
        run: |
          GDBSERVER_PATH=$(find / -name gdbserver 2>/dev/null)
          echo "GDBSERVER_PATH=$GDBSERVER_PATH" >> $GITHUB_ENV

      - name: Upload gdbserver artifact
        if: env.GDBSERVER_PATH != ''
        uses: actions/upload-artifact@v3
        with:
          name: gdbserver
          path: ${{ env.GDBSERVER_PATH }}
